"""Deterministic settings screenshot data, passed only in debug reference mode."""
TABS = [("general", "General"), ("predictive", "Análisis predictivo"),
        ("notifications", "Notificaciones"), ("users", "Usuarios y roles"),
        ("security", "Seguridad"), ("integrations", "Integraciones"), ("backup", "Respaldo")]
SETTINGS = {
    "general": [
        ("Nombre de la empresa", "Ferretería Pro C.A.", False),
        ("Sucursal activa", "Sucursal Principal (Valencia)", True),
        ("Zona horaria", "(GMT-04:00) Caracas", True),
        ("Moneda", "USD - Dólar estadounidense (US$)", True),
        ("Idioma", "Español (España)", True),
        ("Formato de fecha", "DD/MM/YYYY", True),
    ],
    "preferences": [
        ("boxes", "Control de stock mínimo", "Enviar alertas cuando el stock esté por debajo del mínimo.", True),
        ("chart", "Sugerencias de reabastecimiento", "Mostrar sugerencias automáticas de compra.", True),
        ("chart", "Análisis de estacionalidad", "Incluir factores estacionales en los pronósticos.", True),
        ("search", "Detección de outliers", "Detectar y excluir valores atípicos en el análisis.", True),
        ("sliders", "Redondeo de cantidades", "Redondear sugerencias de compra a múltiplos.", False),
        ("clipboard", "Precios con impuestos incluidos", "Mostrar precios finales con impuestos.", True),
    ],
    "general_parameters": [
        ("Horizonte de pronóstico", "Número de días para generar pronósticos de demanda.", "30", "días"),
        ("Nivel de confianza", "Nivel de confianza para los intervalos de predicción.", "95%", "select"),
        ("Actualización automática de modelos", "Frecuencia para reentrenar los modelos predictivos.", "Semanal", "select"),
    ],
    "units": [("Unidad de medida base", "Unidad (ud.)"), ("Peso base", "Kilogramo (kg)"), ("Longitud base", "Metro (m)")],
    "system": [("Versión de la aplicación", "v2.1.0"), ("Versión del modelo predictivo", "v2.1.0"), ("Última actualización", "30/05/2024 08:45")],
    "storage": "2.4 GB / 10 GB", "storage_percent": 24,
    "activity": [
        ("settings", "Configuración general actualizada", "30/05/2024", "08:45"),
        ("chart", "Parámetros predictivos modificados", "29/05/2024", "16:30"),
        ("bell", "Notificaciones configuradas", "28/05/2024", "11:15"),
        ("users", "Usuario nuevo creado", "27/05/2024", "09:20"),
        ("lock", "Políticas de seguridad actualizadas", "26/05/2024", "14:10"),
    ],
    "models": [
        ("Modelo de pronóstico de demanda", "Modelo principal utilizado para predecir la demanda futura.", "Prophet (Meta)"),
        ("Modelo de estacionalidad", "Modelo auxiliar para detectar patrones estacionales.", "SARIMA"),
        ("Modelo de suavizado", "Método de suavizado para reducir el ruido en las predicciones.", "Suavizado exponencial (Holt-Winters)"),
    ],
    "forecast": [
        ("Horizonte de pronóstico", "Número de días hacia el futuro a predecir.", "30", "días"),
        ("Nivel de confianza", "Nivel de confianza para los intervalos de predicción.", "95%", "select"),
        ("Frecuencia de actualización", "Cada cuánto se recalculan las predicciones.", "Diaria", "select"),
        ("Ventana histórica utilizada", "Período de datos históricos para entrenar los modelos.", "365", "días"),
        ("Umbral de detección de cambio", "Sensibilidad para detectar cambios en la demanda.", "15", "%"),
    ],
    "variables": [
        ("Ventas históricas", "Historial de ventas por producto."),
        ("Estacionalidad", "Patrones por día de la semana y mes del año."),
        ("Tendencia", "Tendencia general de crecimiento o decrecimiento."),
        ("Días festivos", "Impacto de feriados y eventos especiales."),
        ("Promociones", "Efecto de promociones y descuentos."),
        ("Precio del producto", "Variaciones de precio en el tiempo."),
    ],
    "thresholds": [
        ("Umbral de error aceptable (MAPE)", "Error máximo aceptable del modelo.", "20", "%"),
        ("Umbral de alerta de demanda", "Variación mínima para generar alerta.", "15", "%"),
        ("Productos mínimos para entrenamiento", "Cantidad mínima de ventas históricas requeridas.", "30", "registros"),
    ],
    "model_status": [("clipboard", "Último entrenamiento", "30/05/2024 02:15 AM"),
                     ("clipboard", "Próximo entrenamiento", "03/06/2024 02:00 AM"),
                     ("chart", "MAPE actual", "7.6%"), ("shield", "Estado", "Excelente")],
    "training_time": "02:00 AM", "training_day": "Lunes",
    "notification_channels": [
        ("bell", "blue", "Notificaciones en la app", "Muestra alertas en el panel de notificaciones del sistema.", True, True),
        ("mail", "purple", "Correo electrónico", "Recibe notificaciones en tu correo institucional.", True, True),
        ("phone", "green", "WhatsApp", "Recibe alertas importantes por WhatsApp.", False, False),
        ("message", "orange", "SMS", "Recibe notificaciones por mensaje de texto.", False, False),
    ],
    "notification_events": [
        ("boxes", "Stock bajo", "Productos con inventario por debajo del mínimo.", [True, True, False, False]),
        ("truck", "Reabastecimiento sugerido", "Recomendaciones de compra por análisis predictivo.", [True, True, False, False]),
        ("cart", "Ventas y pedidos", "Nuevos pedidos, ventas y cambios en el estado.", [True, True, True, False]),
        ("alert", "Productos críticos", "Productos con alto riesgo de quiebre.", [True, True, True, True]),
        ("settings", "Mantenimiento del sistema", "Actualizaciones, respaldos y tareas programadas.", [True, True, False, False]),
        ("shield", "Alertas de seguridad", "Intentos de acceso, cambios de contraseña y más.", [True, True, True, False]),
    ],
    "notification_email": "notificaciones@ferreteriapro.com",
    "notification_frequency": "Diario", "notification_time": "08:00 AM", "notification_format": "HTML",
    "recent_notifications": [
        ("alert", "red", "Stock bajo", "El producto Cemento Portland 50 kg tiene solo 16 unidades.", "Hace 2 horas", "Correo"),
        ("cart", "green", "Nuevo pedido", "Pedido #000245 por $248.50 realizado por Cliente #1032.", "Hace 4 horas", "App"),
        ("chart", "purple", "Recomendación de compra", "Se sugiere reabastecer Pintura Blanca 18 L en 10 días.", "Hace 6 horas", "App"),
        ("shield", "blue", "Inicio de sesión", "Nuevo inicio de sesión desde IP 192.168.1.45.", "Hace 8 horas", "Correo"),
    ],
    "users": [
        ("Administrador", "admin", "Administrador", "AD", "blue", True),
        ("Isabel Vivas", "isabel.vivas", "Inventario", "IV", "teal", True),
        ("Marcos Colina", "marcos.colina", "Vendedor", "MC", "purple", True),
        ("Luis Alvarado", "luis.alvarado", "Vendedor", "LA", "purple", True),
        ("José Rivero", "jose.rivero", "Compras", "JR", "orange", True),
        ("Paola Figueroa", "paola.figueroa", "Contabilidad", "PF", "pink", False),
        ("Eduardo Blanco", "eduardo.blanco", "Inventario", "EB", "blue", False),
    ],
    "user_details": [("Nombre completo", "Administrador"), ("Correo electrónico", "admin@ferreteriapro.com"), ("Teléfono", "xxx xxx xxxx")],
    "user_id": "U-0001", "user_last_access": "30/05/2024 08:15 AM", "user_created": "12/01/2024 10:30 AM",
    "password_policy": [
        ("Longitud mínima", "8 caracteres"), ("Mayúsculas", "Al menos 1"),
        ("Minúsculas", "Al menos 1"), ("Números", "Al menos 1"),
        ("Caracteres especiales", "Al menos 1"), ("Expiración de contraseña", "90 días"),
        ("Historial de contraseñas", "No repetir últimas 5"),
    ],
    "security_access": [
        ("lock", "Contraseña segura", "Usa una contraseña fuerte para proteger tu cuenta.", "Cambiar contraseña"),
        ("shield", "Autenticación en dos pasos (2FA)", "Añade una capa adicional de seguridad a tu cuenta.", None),
        ("users", "Cerrar sesión en todos los dispositivos", "Finaliza todas las sesiones activas, excepto la actual.", "Cerrar todas las sesiones"),
    ],
    "mfa_method": "Aplicación autenticadora (Google Authenticator)",
    "backup_code_summary": "10 códigos disponibles",
    "security_sessions": [
        ("monitor", "Windows / Chrome", True, "Valencia, Carabobo", "190.12.45.67", "30/05/2024 08:15 AM", True),
        ("smartphone", "Android / Chrome", False, "Valencia, Carabobo", "190.12.45.68", "29/05/2024 05:42 PM", True),
        ("smartphone", "iPhone / Safari", False, "Valencia, Carabobo", "190.12.45.69", "28/05/2024 09:21 AM", True),
        ("monitor", "Windows / Edge", False, "Maracay, Aragua", "181.23.11.22", "27/05/2024 11:03 AM", False),
    ],
    "login_history": [
        ("30/05/2024 08:15 AM", "190.12.45.67", "Valencia, Carabobo", True),
        ("29/05/2024 05:42 PM", "190.12.45.68", "Valencia, Carabobo", True),
        ("29/05/2024 04:10 PM", "201.234.12.10", "Caracas, Distrito Capital", False),
        ("28/05/2024 09:21 AM", "190.12.45.69", "Valencia, Carabobo", True),
        ("27/05/2024 11:03 AM", "181.23.11.22", "Maracay, Aragua", True),
    ],
    "roles": [
        ("Administrador", "Acceso completo a todas las funciones.", 5, "shield", "purple"),
        ("Inventario", "Gestiona inventario, productos y movimientos.", 2, "boxes", "blue"),
        ("Vendedor", "Realiza ventas y consulta productos.", 2, "cart", "green"),
        ("Compras", "Gestiona compras y proveedores.", 1, "bag", "orange"),
        ("Contabilidad", "Acceso a reportes contables y financieros.", 1, "calculator", "pink"),
    ],
    "role_permissions": [
        ("Inventario", "Ver y gestionar productos, categorías y movimientos.", "boxes", "blue"),
        ("Ventas", "Crear y gestionar ventas, cotizaciones y clientes.", "cart", "green"),
        ("Compras", "Gestionar compras, proveedores y órdenes de compra.", "bag", "orange"),
        ("Reportes", "Acceso completo a todos los reportes del sistema.", "chart", "pink"),
        ("Configuración", "Gestionar configuración general del sistema.", "settings", "blue"),
    ],
    "backup": {
        "status": "Todo correcto", "next": "01/06/2024 02:00 AM",
        "last": "31/05/2024 02:15 AM", "count": 14, "size": "245.8 MB",
        "usage": "3.2 GB de 50 GB (6.4%)", "percent": 6.4,
        "frequency": "Diaria", "time": "02:00 AM", "retention": "30 días",
        "location": "Almacenamiento local (servidor)", "path": "/backups/ferreteria_pro",
        "available": "46.8 GB", "secondary": "Google Drive", "selected_type": "full",
        "selection": "31/05/2024 02:15 AM (245.8 MB)",
        "types": [("full", "Respaldo completo", "Incluye toda la base de datos y archivos."),
                  ("database", "Solo base de datos", "Respalda únicamente la base de datos."),
                  ("files", "Solo archivos", "Respalda archivos y documentos del sistema.")],
        "recommendations": [
            "Realiza respaldos automáticos diarios para proteger tu información.",
            "Almacena respaldos en una ubicación segura y diferente al servidor principal.",
            "Verifica periódicamente que los respaldos se estén creando correctamente.",
            "Restaura un respaldo de prueba de vez en cuando para asegurar su integridad.",
        ],
    },
}
