// Uses scripts/test_settings_reference.py --serve on port 5000, without a database.
const {chromium} = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const output = '.tmp/product-drawer-validation';
fs.mkdirSync(output, {recursive:true});
(async () => {
    const browser = await chromium.launch({channel:'msedge'});
    const page = await browser.newPage({viewport:{width:1600,height:900},deviceScaleFactor:1});
    const mutations = [], errors = [], network = [];
    page.on('request', request => {
        if (request.url().startsWith('http')) network.push(request.url());
        if (!['GET','HEAD','OPTIONS'].includes(request.method())) mutations.push(request.method());
    });
    page.on('pageerror', error => errors.push(error.message));
    const shot = name => page.screenshot({path:`${output}/${name}.png`});
    await page.goto('http://127.0.0.1:5000/products?ref=1', {waitUntil:'networkidle'});
    assert.deepEqual(await page.evaluate(()=>[innerWidth,innerHeight,devicePixelRatio]), [1600,900,1]);
    const base = await page.locator('.iv-prod-body').innerHTML();
    await shot('base-final');
    const trigger = page.getByRole('button',{name:'Nuevo producto',exact:true});
    const drawer = page.locator('#np-drawer');
    await trigger.click();
    await page.waitForTimeout(250);
    await shot('drawer-final');
    assert.deepEqual(await drawer.boundingBox(),{x:1170,y:0,width:430,height:900});
    assert.equal(await page.locator('dialog[open]').count(),1);
    assert.equal(await page.locator('body').evaluate(n=>n.style.overflow),'hidden');
    await page.getByRole('button',{name:'Cancelar',exact:true}).click();
    await drawer.waitFor({state:'hidden'});
    assert(await trigger.evaluate(n=>n===document.activeElement));
    await trigger.click();
    await page.getByRole('button',{name:'Cerrar nuevo producto'}).click();
    await drawer.waitFor({state:'hidden'});
    assert(await trigger.evaluate(n=>n===document.activeElement));
    await trigger.click();
    await page.keyboard.press('Escape');
    await drawer.waitFor({state:'hidden'});
    assert(await trigger.evaluate(n=>n===document.activeElement));
    await trigger.click();
    await page.locator('#np-save').click();
    assert.equal(await page.locator('#np-form [aria-invalid="true"]').count(),6);
    await shot('required-validation');
    for (const [id,value] of Object.entries({name:'Producto de prueba visual',sku:'REF-NUEVO',brand:'Bosch',price:'25.50',cost:'12.25',stock:'8',minimum:'2'})) {
        await page.locator(`#np-${id}`).fill(value);
    }
    for (const id of ['category','supplier','branch','unit']) await page.locator(`#np-${id}`).selectOption({index:1});
    await page.locator('#np-status').selectOption('Bajo stock');
    assert.equal(await page.locator('.np-status').getAttribute('data-status'),'Bajo stock');
    await page.locator('#np-status').selectOption('Disponible');
    await page.locator('#np-description').fill('Descripción de prueba.');
    assert.equal(await page.locator('#np-counter').innerText(),'22/500');
    await page.locator('#np-description').fill('a'.repeat(500));
    await page.locator('#np-description').press('End');
    await page.locator('#np-description').press('b');
    assert.equal((await page.locator('#np-description').inputValue()).length,500);
    assert.equal(await page.locator('#np-counter').innerText(),'500/500');
    const requestCount = network.length;
    await page.locator('#np-image').setInputFiles({name:'preview.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64')});
    await page.waitForFunction(()=>document.getElementById('np-preview-image').naturalWidth>0);
    assert((await page.locator('#np-preview-image').getAttribute('src')).startsWith('blob:'));
    await shot('image-preview');
    assert.equal(network.length,requestCount);
    await page.locator('#np-image').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});
    assert(await page.locator('#np-image-error').isVisible());
    assert(await page.locator('#np-preview-image').isHidden());
    await page.locator('#np-image').setInputFiles({name:'large.png',mimeType:'image/png',buffer:Buffer.alloc(5*1024*1024+1)});
    assert(await page.locator('#np-image-error').isVisible());
    await page.locator('#np-save').click();
    await drawer.waitFor({state:'hidden'});
    assert(await page.locator('#np-feedback').isVisible());
    await shot('simulated-save');
    assert.equal(await page.locator('.iv-prod-body').innerHTML(),base);
    await page.reload({waitUntil:'networkidle'});
    assert.equal(await page.locator('.iv-prod-body').innerHTML(),base);
    for (const route of ['categories','suppliers','inventory','dashboard']) {
        const response=await page.goto(`http://127.0.0.1:5000/${route}?ref=1`,{waitUntil:'networkidle'});
        assert.equal(response.status(),200);
        assert(await page.locator('[aria-controls="ix-nav-pred"]').isVisible());
        assert.equal(await page.locator('#np-drawer').count(),0);
        await shot(`regression-${route}`);
    }
    await page.goto('http://127.0.0.1:5000/products?ref=1',{waitUntil:'networkidle'});
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'Nuevo producto',exact:true}).click();
    await shot('drawer-mobile');
    assert(await page.locator('#np-save').isVisible());
    assert.equal(await drawer.evaluate(n=>n.scrollWidth<=n.clientWidth),true);
    assert.deepEqual(mutations,[]);
    assert.deepEqual(errors,[]);
    console.log('PASS: Chromium 1600x900 DPR1, drawer geometry, X/Cancel/Escape/focus, required validation, all controls, 500 counter, local preview/type/size rejection, simulated save/reload, 4 regressions, mobile; zero mutation requests or JS errors');
    await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
